backend/backend/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
   path('admin/',admin.site.urls),
   path('base/',include(('base.urls',"base"),namespace="base")),
   path('',include(('shop.urls',"shop"),namespace="shop")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

    

backend/base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.IndexView.as_view(),name='home'),
    path('graph',views.graph_view,name='graph'),
    path('export-csv',views.export,name='exportcsv'),
    path('login/', views.User_login.as_view(), name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('adminUsers/create', views.AddAdminUserView.as_view(),name="adminUsersCreate"),
    path('adminUsers/', views.AdminUserListView,name="adminUsersList"),
    path('costumerUsers/', views.CostumerUserListView,name="costumerUsersList"),
    path('products/create',views.ProductView.as_view(),name='productCreate'),
    path('products/',views.ProductListView.as_view(),name='productList'),
    path('products/<int:idp>/update',views.ProductUpdateView.as_view(),name='productUpdate'),
    path('products/<int:idp>/delete',views.ProductDeleteView.as_view(),name='productDelete'),
    path('products/<int:idp>/details',views.ProductDetailsView.as_view(),name='productDetails'),
    path('categories/create',views.CategoryView.as_view(),name='categoryCreate'),
    path('categories/',views.CategoryListView.as_view(),name='categoryList'),
    path('categories/<int:idp>/delete',views.CategoryDeleteView.as_view(),name='categoryDelete'),
    path('categories/<int:idp>/details',views.CategoryDetailsView.as_view(),name='categoryDetails'),
    path('categories/<int:idp>/update',views.CategoryUpdateView.as_view(),name='categoryUpdate'),
    path('Commandes/', views.order_history, name='history'),


   ]

backend/base/models.py
from django.db import models
from django import forms
from shop.models import *
# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=100)
    description=models.TextField()
    image=models.ImageField(upload_to="images/",default=None)
    def __str__(self):
        return self.name

class Product(models.Model):
    name= models.CharField(max_length=100)
    description=models.TextField()
    brand=models.CharField(max_length=100)
    price=models.FloatField()
    countInStock=models.IntegerField()
    image=models.ImageField(upload_to="images/")
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    def __str__(self):
        return self.name


class Order(models.Model):
    CASABLANCA = 'Casablanca'
    RABAT = 'Rabat'
    SETTAT = 'Settat'

    CITY = (
    (CASABLANCA,'Casablanca'),
    (RABAT,'Rabat'),
    (SETTAT,'Settat'),
    )
    costumer=models.ForeignKey(Costumer,on_delete=models.CASCADE)
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=12,default=CASABLANCA,choices=CITY,blank=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

class OrderItem(models.Model):
    order = models.ForeignKey(Order,related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product,related_name='order_items',on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

class AdminUser(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='admins/',blank=True)

backend/base/forms.py
from django import forms
from .models import *

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"
        labels={"name":"Nom",
                "description":"Description",
                "brand":"Marque",
                "price":"Prix",
                "countInStock":"Quantité en stock",
                "category":"Catégorie"}

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = "__all__"
        labels={"name":"Nom",
                "description":"Description"}

class AdminUserForm(forms.ModelForm):
    class Meta:
        model = AdminUser
        fields = ('date_of_birth', 'photo')
        labels={"date_of_birth":"Date de naissance"}

backend/base/views.py
from django.shortcuts import render,redirect
from django.views import View
from .models import *
from .forms import *
from shop.models import *
from shop.forms import *
from django.http import HttpResponse
import csv
from .utils import get_plot
import pandas as pd
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.models import Group

def has_group(user, group):
    return user.groups.filter(name=group).exists()



# Create your views here.
class ProductView(UserPassesTestMixin,View):
    def test_func(self):
        qs=self.request.user
        return has_group(qs,'admins')
    def get(self,request):
        form=ProductForm()
        return render(request,"admins/product_form.html",{'form':form})
    def post(self,request):
        form=ProductForm(request.POST,request.FILES)
        if form.is_valid():
           form.save()
        return redirect("base:productList")
        
class CategoryView(UserPassesTestMixin,View):
    def test_func(self):
        qs=self.request.user
        return has_group(qs,'admins')
    def get(self,request):
        form=CategoryForm()
        return render(request,"admins/category_form.html",{'form':form})
    def post(self,request):
        form=CategoryForm(request.POST,request.FILES)
        if form.is_valid():
           form.save()
        return redirect("base:categoryList")

class ProductUpdateView(UserPassesTestMixin,View):
    def test_func(self):
        qs=self.request.user
        return has_group(qs,'admins')
    def get(self,request,idp):
        product=Product.objects.get(id=idp)
        form=ProductForm(instance=product)
        return render(request,"admins/product_form.html",{'form':form})
    def post(self,request,idp):
        product=Product.objects.get(id=idp)
        form=ProductForm(request.POST,request.FILES,instance=product)
        if form.is_valid():
           form.save()
        return redirect("base:productList")

class CategoryUpdateView(UserPassesTestMixin,View):
    def test_func(self):
        qs=self.request.user
        return has_group(qs,'admins')
    def get(self,request,idp):
        category=Category.objects.get(id=idp)
        form=CategoryForm(instance=category)
        return render(request,"admins/category_form.html",{'form':form})
    def post(self,request,idp):
        category=Category.objects.get(id=idp)
        form=CategoryForm(request.POST,request.FILES,instance=category)
        if form.is_valid():
           form.save()
        return redirect("base:categoryList")

class ProductDeleteView(UserPassesTestMixin,View):
    def test_func(self):
        qs=self.request.user
        return has_group(qs,'admins')
    def get(self,request,idp):
        return render(request,"admins/delete_form.html",{})
    def post(self,request,idp):
        product=Product.objects.get(id=idp)
        product.delete()
        return redirect("base:productList")

class CategoryDeleteView(UserPassesTestMixin,View):
    def test_func(self):
        qs=self.request.user
        return has_group(qs,'admins')
    def get(self,request,idp):
        return render(request,"admins/catdelete_form.html",{})
    def post(self,request,idp):
        category=Category.objects.get(id=idp)
        category.delete()
        return redirect("base:categoryList")

class ProductDetailsView(UserPassesTestMixin,View):
    def test_func(self):
        qs=self.request.user
        return has_group(qs,'admins')
    def get(self,request,idp):
        product=Product.objects.get(id=idp)
        return render(request,"admins/product_details.html",{'product':product})

class CategoryDetailsView(UserPassesTestMixin,View):
    def test_func(self):
        qs=self.request.user
        return has_group(qs,'admins')
    def get(self,request,idp):
        category=Category.objects.get(id=idp)
        return render(request,"admins/category_details.html",{'category':category})


class IndexView(UserPassesTestMixin,View):
    def test_func(self):
        qs=self.request.user
        return has_group(qs,'admins')
    def get(self, request):
        return render(request,"admins/base.html",{})

class ProductListView(UserPassesTestMixin,View):
    def test_func(self):
        qs=self.request.user
        return has_group(qs,'admins')
    def get(self,request):
        products=Product.objects.all()
        return render(request,"admins/product_list.html",{'products':products})

class CategoryListView(UserPassesTestMixin,View):
    def test_func(self):
        qs=self.request.user
        return has_group(qs,'admins')
    def get(self,request):
        categories=Category.objects.all()
        return render(request,"admins/category_list.html",{'categories':categories})


def export(request):
    response= HttpResponse(content_type='text/csv')
    writer=csv.writer(response,delimiter=',')
    writer.writerow(['name','description','brand','price','countInStock','category'])
    for task in Product.objects.all().values_list('name','description','brand','price','countInStock','category'):
        writer.writerow(task)
    response['Content-Disposition']= 'attachement ; filename="Product.csv"'
    return response


def graph_view(request):
    qs=OrderItem.objects.all()
    x=[x.product.name for x in qs]
    y=[y.quantity for y in qs]
    chart=get_plot(x,y)
    return render(request,"admins/graph.html",{'chart':chart})



class AddAdminUserView(View):
    def get(self,request):
        user_form = UserForm()
        admin_form = AdminUserForm(request.POST)
        return render(request,'admins/admin_form.html',{'user_form': user_form,'admin_form':admin_form})
    def post(self,request):
        user_form = UserForm(request.POST)
        admin_form = AdminUserForm(request.POST,request.FILES)

        if user_form.is_valid() and admin_form.is_valid():
            new_user = user_form.save(commit=False)
            # Définir le mot de passe choisi
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.is_admin=True
            
            new_user.save()
            group = Group.objects.get(name='admins')
            new_user.groups.add(group)
            new_admin=admin_form.save(commit=False)
            new_admin.user=new_user
            new_admin.save()
            return render(request,'admins/admin_users_list.html',{'new_user': new_user})
        return HttpResponse('Données invalides')

def AdminUserListView(request):
        adminUsers=AdminUser.objects.all()
        return render(request,"admins/admin_users_list.html",{'adminUsers':adminUsers})

def CostumerUserListView(request):
        costumers=Costumer.objects.all()
        return render(request,"admins/Costumer_users_list.html",{'costumers':costumers})


class User_login(View):
    def get(self,request):
        form = LoginForm()
        return render(request, 'admins/login.html', {'form': form})
    def post(self,request):
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,username=cd['username'],password=cd['password'])
            if user is not None:
                if user.is_active and user.is_admin:
                    login(request, user)
                    return redirect("base:productList")
                else:
                    return HttpResponse("you're not an admin")
            else:
                return HttpResponse('Invalid login')
        return redirect("base:home")

def user_logout(request):
    logout(request)
    return redirect("shop:shop")


def order_history(request):
    orders = Order.objects.all()
    return render(request, "admins/commandes_list.html", {'orders':orders})

backend/templates/admins/admin_form.html
{% extends 'admins/base.html' %}
{% block title %} Ajouter un administrateur {% endblock %}
{% block content %}

{%load crispy_forms_tags%}

            <!-- page content -->
            <div class="right_col" role="main">
                <div class="">
                    <div class="page-title">
                        <div class="title_left">
                            <h3>New admin user</h3>
                        </div>

                        <div class="title_right">
                            <div class="col-md-5 col-sm-5 form-group pull-right top_search">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Search for...">
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="button">Go!</button>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="clearfix"></div>

                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <div class="x_panel">
                                <div class="x_title">
                                    <h2>Ajouter un admin <small>formulaire</small></h2>
                                    <ul class="nav navbar-right panel_toolbox">
                                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                        </li>
                                        <li><a class="close-link"><i class="fa fa-close"></i></a>
                                        </li>
                                    </ul>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="x_content">
                                    <form class="" action="{% url 'base:productCreate' %}" method="POST" >
                                        {{ user_form|crispy }}
                                        {{ admin_form|crispy }}
                                        {% csrf_token %}
                                        

                                        <div class="ln_solid">
                                            <div class="form-group">
                                                <div class="col-md-6 offset-md-3">
                                                    <button type='submit' class="btn btn-primary">Submit</button>
                                                    <button type='reset' class="btn btn-success">Reset</button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

    {% endblock %}

backend/templates/admins/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load static %}
    <title> {% block title %} Administration {% endblock %} </title>
    {% block stylesheet %} 
    <!-- Bootstrap -->
    <link href="{% static 'dash/vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'dash/vendors/font-awesome/css/font-awesome.min.css' %}"  rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'dash/vendors/nprogress/nprogress.css' %}"  rel="stylesheet">
    <!-- bootstrap-progressbar -->
    <link href="{% static 'dash/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css' %}"  rel="stylesheet">
    <!-- bootstrap-daterangepicker -->
    <link href="{% static 'dash/vendors/bootstrap-daterangepicker/daterangepicker.css' %}"  rel="stylesheet">
    
    <!-- Custom Theme Style -->
    
    <link href="{% static 'dash/build/css/custom.min.css' %}"  rel="stylesheet">
    


    {% endblock %}
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="{% url 'base:home' %}" class="site_title"><i class="fa fa-square"></i> <span>Home</span></a>
            </div>

            <div class="clearfix"></div>
            {% if request.user.is_authenticated and not request.user.is_costumer%}
            <!-- menu profile quick info -->
            <div class="profile clearfix">
              <div class="profile_pic">
                <img src="{{request.user.admin.photo.url}}" >
              </div>
              <div class="profile_info">
                <span>Welcome,</span>
                <h2> {{request.user.first_name}}</h2>
              </div>
            </div>
            {%endif%}
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                  
                  <li><a><i class="fa fa-clone"></i>Produits <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{% url 'base:productList' %}">List de produits</a></li>
                      <li><a href="{% url 'base:productCreate' %}">Ajouter un produits</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-archive"></i>Categories <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{% url 'base:categoryList' %}">List de categories</a></li>
                      <li><a href="{% url 'base:categoryCreate' %}">Ajouter une category</a></li>
                    </ul>
                  </li>
                  
                  <li><a><i class="fa fa-users"></i> Utilisateurs <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="{% url 'base:adminUsersList' %}">Admins</a>
                        
                        <li><a href="{% url 'base:costumerUsersList' %}">Costumers</a>
                        </li>
                    </ul>
                  </li>                  
                  <li><a href="{% url 'base:history' %}"><i class="fa fa-history"></i> Commandes </a></li>
                  <li><a href="{% url 'base:graph' %}"><i class="fa fa-bar-chart"></i> Graph </a></li>

                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
              <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="login" href="{% url 'base:login' %}">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>
            <!-- /menu footer buttons -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
            <div class="nav_menu">
                <div class="nav toggle">
                  <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                </div>
                <nav class="nav navbar-nav">
                <ul class=" navbar-right">
                  <li class="nav-item dropdown open" style="padding-left: 15px;">
                    <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
                      {{request.user.first_name}}
                    </a>
                    <div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">
                      
                      <a class="dropdown-item"  href="{% url 'base:logout' %}"><i class="fa fa-sign-out pull-right"></i> Log Out</a>
                    </div>
                  </li>
  
                    </ul>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        <!-- /top navigation -->

        <!-- page content -->
        {% block content %}
        {% endblock %}
        </div>
        <!-- /page content -->

        <!-- footer content -->
        {% block footer %}
        <footer>
          <div class="pull-right">
            Credit: Bootstrap Template by <a href="https://colorlib.com">Colorlib</a>
          </div>
          <div class="clearfix"></div>
        </footer>
        {% endblock %}
        <!-- /footer content -->
      </div>
    </div>
    {% block javascripts %}
    <!-- jQuery -->
    <script src="{% static 'dash/vendors/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
   <script src="{% static 'dash/vendors/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'dash/vendors/fastclick/lib/fastclick.js' %}"></script>
    <!-- NProgress -->
    <script src="{% static 'dash/vendors/nprogress/nprogress.js' %}"></script>
    <!-- Chart.js -->
    <script src="{% static 'dash/vendors/Chart.js/dist/Chart.min.js' %}"></script>
    <!-- jQuery Sparklines -->
    <script src="{% static 'dash/vendors/jquery-sparkline/dist/jquery.sparkline.min.js' %}"></script>
    <!-- morris.js -->
    <script src="{% static 'dash/vendors/raphael/raphael.min.js' %}"></script>
    <script src="{% static 'dash/vendors/morris.js/morris.min.js' %}"></script>
    <!-- gauge.js -->
    <script src="{% static 'dash/vendors/gauge.js/dist/gauge.min.js' %}"></script>
    <!-- bootstrap-progressbar -->
    <script src="{% static 'dash/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js' %}"></script>
    <!-- Skycons -->
    <script src="{% static 'dash/vendors/skycons/skycons.js' %}"></script>
    <!-- Flot -->
    <script src="{% static 'dash/vendors/Flot/jquery.flot.js' %}"></script>
    <script src="{% static 'dash/vendors/Flot/jquery.flot.pie.js' %}"></script>
    <script src="{% static 'dash/vendors/Flot/jquery.flot.time.js' %}"></script>
    <script src="{% static 'dash/vendors/Flot/jquery.flot.stack.js' %}"></script>
    <script src="{% static 'dash/vendors/Flot/jquery.flot.resize.js' %}"></script>
    <!-- Flot plugins -->
    <script src="{% static 'dash/vendors/flot.orderbars/js/jquery.flot.orderBars.js' %}"></script>
    <script src="{% static 'dash/vendors/flot-spline/js/jquery.flot.spline.min.js' %}"></script>
    <script src="{% static 'dash/vendors/flot.curvedlines/curvedLines.js' %}"></script>
    <!-- DateJS -->
    <script src="{% static 'dash/vendors/DateJS/build/date.js' %}"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="{% static 'dash/vendors/moment/min/moment.min.js' %}"></script>
    <script src="{% static 'dash/vendors/bootstrap-daterangepicker/daterangepicker.js' %}"></script>

    <!-- Custom Theme Scripts -->
    <script src="{% static 'dash/build/js/custom.min.js' %}"></script>
    <script src="{% static 'dash/vendors/jszip/dist/jszip.min.js' %}"></script>
    <script src="{% static 'dash/vendors/pdfmake/build/pdfmake.min.js' %}"></script>
    <script src="{% static 'dash/vendors/pdfmake/build/vfs_fonts.js' %}"></script>
    {% endblock  %}
  </body>
</html>

backend/templates/admins/catdelete_form.html
<form method="POST">
    {%csrf_token%}
    <input type="submit" value="Oui">
    <a href="{% url 'base:categoryList' %}" >Annuler</a>
    
    </form>

backend/templates/admins/category_details.html
{% extends 'admins/base.html' %}
{% block title %} Details {% endblock %}
{% block content %}

 <!-- page content -->
 <div class="right_col" role="main">

    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>E-commerce ::  Categorie</h3>
        </div>

        <div class="title_right">
          <div class="col-md-5 col-sm-5  form-group pull-right top_search">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-default" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>
      </div>
      
      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12 col-sm-12 ">
          <div class="x_panel">
            <div class="x_title">
              <h2>E-commerce</h2>
              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">

              <div class="col-md-7 col-sm-7 ">
                <div class="product-image">
                    <img src="{{category.image.url}}" alt="..." />
                </div>
                
              </div>

              <div class="col-md-5 col-sm-5 " style="border:0px solid #e5e5e5;">

                <h3 class="prod_title">{{category.name}}</h3>

                <p>{{category.description}}.</p>
                <br />
            
                <br />

                
                <br />

                
                <div class="">
                  <button type="button" class="btn btn-default btn-lg">ID: {{category.id}}</button>
                </div>

                <div class="product_social">
                  <ul class="list-inline display-layout">
                    <li><a href="#"><i class="fa fa-facebook-square"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-twitter-square"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-envelope-square"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-rss-square"></i></a>
                    </li>
                  </ul>
                </div>

              </div>


              

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /page content -->






{% endblock  %}

backend/templates/admins/category_list.html
{% extends 'admins/base.html' %}
{% block title %} List de categories {% endblock %}
{% block content %}

<div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Table <small>detaillée </small></h3>
        </div>

        <div class="title_right">
          <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>
      </div>
      <div class="clearfix"></div>
<div class="col-md-12 col-sm-12 ">
    <div class="x_panel">
      <div class="x_title">
        <h2>List de categories <small>informations</small></h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
          <div class="row">
              <div class="col-sm-12">
                <div class="card-box table-responsive">
        <p class="text-muted font-13 m-b-30">
            Appuier sur details pour plus de detail
        </p>
        
        <table id="datatable-buttons" class="table table-striped table-bordered" style="width:100%">
          <thead>
            <tr>
                    <th>ID</th>
                    <th>Nom</th>
                    <th>Description</th>
                    <th>Image</th>
                    <th>Modifier</th>
                    <th>Supprimer</th>
                    <th>Details</th>
            </tr>
          </thead>


          <tbody>
            {% for category in categories%}
            <tr>
                <th>{{category.id}}</th>
                <td>{{category.name}}</td>
                <td>{{category.description}}</td>
                <td><img style="width: 100%; display: block;"  src="{{category.image.url}}"> </td> 
                <td><a href="{% url 'base:categoryUpdate' category.id %}"> Modifier </a></td>
                <td><a href="{% url 'base:categoryDelete' category.id %}">Supprimer</a></td>
                <td><a href="{% url 'base:categoryDetails' category.id %}">Details</a></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
    </div>
  </div>
</div></div>
{% endblock %}


  

backend/templates/admins/delete_form.html
<form method="POST">
{%csrf_token%}
<input type="submit" value="Oui">
<a href="{% url 'base:productList' %}" >Annuler</a>

</form>

backend/templates/admins/index.html
{% extends 'admin/base.html' %}
{% block title %} Accueil {% endblock %}
{% block content %}
{% endblock %}

backend/templates/admins/login.html
{% extends "admin/base.html" %}
{% block title %}Connexion{% endblock %}
{%load crispy_forms_tags%}
{% block content %}
<section class="section-conten padding-y" style="min-height:84vh">
   <!-- ============================ COMPONENT LOGIN   ================================= -->
      <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
         <div class="card-body">
         <h4 class="card-title mb-4">Se connecter</h4>
         <form action="{% url 'base:login' %}" method="post">
            <div class="form-group">
            {{ form|crispy }}
         </div>
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}" />
            <p><input type="submit" value="Connexion"></p>
         </form>
         </div> <!-- card-body.// -->
       </div> <!-- card .// -->

   </section>
{% endblock %}