backend/backend/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
   path('admin/',admin.site.urls),
   path('base/',include(('base.urls',"base"),namespace="base")),
   path('',include(('shop.urls',"shop"),namespace="shop")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

    

backend/base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.IndexView.as_view(),name='home'),
    path('graph',views.graph_view,name='graph'),
    path('export-csv',views.export,name='exportcsv'),
    path('login/', views.User_login.as_view(), name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('adminUsers/create', views.AddAdminUserView.as_view(),name="adminUsersCreate"),
    path('adminUsers/', views.AdminUserListView,name="adminUsersList"),
    path('costumerUsers/', views.CostumerUserListView,name="costumerUsersList"),
    path('products/create',views.ProductView.as_view(),name='productCreate'),
    path('products/',views.ProductListView.as_view(),name='productList'),
    path('products/<int:idp>/update',views.ProductUpdateView.as_view(),name='productUpdate'),
    path('products/<int:idp>/delete',views.ProductDeleteView.as_view(),name='productDelete'),
    path('products/<int:idp>/details',views.ProductDetailsView.as_view(),name='productDetails'),
    path('categories/create',views.CategoryView.as_view(),name='categoryCreate'),
    path('categories/',views.CategoryListView.as_view(),name='categoryList'),
    path('categories/<int:idp>/delete',views.CategoryDeleteView.as_view(),name='categoryDelete'),
    path('categories/<int:idp>/details',views.CategoryDetailsView.as_view(),name='categoryDetails'),
    path('categories/<int:idp>/update',views.CategoryUpdateView.as_view(),name='categoryUpdate'),
    path('Commandes/', views.order_history, name='history'),


   ]

backend/shop/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',views.IndexView.as_view(),name="shop"),
    path('products/', views.ProductListView.as_view(),name="productList"),
    path('caregories/<int:idc>/products/', views.ProductsByCategoryView.as_view(),name="productByCetgorie"),
    path('register/', views.Register.as_view(), name='register'),
    path('login/', views.User_login.as_view(), name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('cart/add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('cart/', views.cart_detail,name='cart_detail'),
    path('cart/remove/<int:product_id>/', views.cart_remove,name='cart_remove'),
    path('cart/update/<int:product_id>/', views.cart_update, name='cart_update'),
    path('create/', views.order_create, name='order_create'),
    path('rechercher/', views.rechercher, name='rechercher'),
    path('mescommandes/<int:user_id>/', views.order_history, name='history'),



]



backend/shop/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    is_costumer = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

class Costumer(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='costumers/',blank=True)

class Contact(models.Model):
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()

    def __str__(self):
        return self.email

backend/shop/forms.py
from django import forms
from base.models import Order
from .models import *
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit
class UserForm(forms.ModelForm):
    password = forms.CharField(label='Le mot de passe"',widget=forms.PasswordInput)
    password2 = forms.CharField(label='Répéter le mot de passe',widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('first_name', 'last_name','username', 'email')
        labels={"first_name":"Prénom",
                "last_name":"Nom",
                "username":"Nom d'utilisateur",
                "email":"Email"}
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']
   
class CostumerForm(forms.ModelForm):
    class Meta:
        model = Costumer
        fields = ('date_of_birth', 'photo')
        labels={"date_of_birth":"Date de naissance"}
    
class LoginForm(forms.Form):
    username = forms.CharField(label="Nom d'utilisateur")
    password = forms.CharField(widget=forms.PasswordInput,label="le mot de passe")
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 50)]
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
    class Meta:
        labels={"quantity":"Quantité"}
class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['address','postal_code', 'city']
        labels={"address":"Adresse",
                "postal_code":"Code postal",
                "city":"Ville"}
class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'
        

backend/shop/views.py
from django.shortcuts import render,redirect
from django.views import View
from base.models import *
from .forms import *
from django.contrib.auth import authenticate, login,logout
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render
from .forms import ContactForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.decorators import login_required

# Create your views here.
def has_group(user, group):
    return user.groups.filter(name=group).exists()

def rechercher(request):
    products=Product.objects.filter(name__icontains=request.POST.get("cle"))
    return render(request,"clients/product_list.html",{'products':products})

class IndexView(View):
    def get(self,request):
        products=Product.objects.all()
        cart_product_form = CartAddProductForm()
        contactform=ContactForm()
        return render(request,"clients/index.html",{'products':products,'cart_product_form':cart_product_form,'contactform':contactform})
    def post(self,request):
        contactform=ContactForm(request.POST,request.FILES)
        if contactform.is_valid():
           contactform.save()
           email_subject = f'New contact {contactform.cleaned_data["email"]}: {contactform.cleaned_data["subject"]}'
           email_message = contactform.cleaned_data['message']
           send_mail(email_subject, email_message, settings.CONTACT_EMAIL, settings.ADMIN_EMAIL)
        else:
            return HttpResponse('Données invalides')
        return redirect("shop:shop")



class ProductListView(View):
    def get(self,request):
        products=Product.objects.all()
        cart_product_form = CartAddProductForm()
        return render(request,"clients/product_list.html",{'products':products,'cart_product_form':cart_product_form})
        
class ProductsByCategoryView(View):
    def get(self,request,idc):
        products=Product.objects.filter(category_id=idc)
        return render(request,"clients/product_list.html",{'products':products})

class Register(View):
    def get(self,request):
        user_form = UserForm()
        costumer_form = CostumerForm()
        return render(request,'clients/register.html',{'user_form': user_form,'costumer_form':costumer_form})
    def post(self,request):
        user_form = UserForm(request.POST)
        costumer_form = CostumerForm(request.POST,request.FILES)

        if user_form.is_valid() and costumer_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.is_costumer=True
            
            new_user.save()
            group = Group.objects.get(name='costumers')
            new_user.groups.add(group) 
            new_costumer=costumer_form.save(commit=False)
            new_costumer.user=new_user
            new_costumer.save()
            return render(request,'clients/shop.html',{'new_user': new_user})
        return HttpResponse('Données invalides')

class User_login(View):
    def get(self,request):
        form = LoginForm()
        return render(request, 'clients/login.html', {'form': form})
    def post(self,request):
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,username=cd['username'],password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    if user.is_admin:
                        return redirect('base:home')
                    else :
                        return redirect('shop:shop')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Données invalides')
        return redirect("shop:shop")

def user_logout(request):
    logout(request)
    return redirect('shop:shop')

def cart_add(request, product_id):
    cart = request.session.get(settings.CART_SESSION_ID,{})
    product = Product.objects.get(id=product_id)
    product_id = str(product.id)
    if product_id not in cart:
            cart[product_id] = {'quantity': 1,'price': product.price}

    request.session[settings.CART_SESSION_ID]=cart

    return redirect('shop:productList')

def cart_detail(request):
    cart = request.session.get(settings.CART_SESSION_ID,{})
    cart_total_price=0

    for key,val in cart.items():
        product = Product.objects.get(id=key)
        cart[str(product.id)]['product']=product
        cart[str(product.id)]['price'] = product.price
        cart[str(product.id)]['total_price'] = float(cart[str(product.id)]['price']) * float(cart[str(product.id)]['quantity'])
        cart_total_price+=cart[str(product.id)]['total_price']
    
    return render(request, 'clients/shopcart.html', {'cart': cart,'cart_total_price':cart_total_price})

def cart_update(request, product_id):
    cart = request.session.get(settings.CART_SESSION_ID)
    product = Product.objects.get(id=product_id)
    cart[str(product_id)]['quantity']=request.POST.get('quantity')
    request.session[settings.CART_SESSION_ID]=cart

    return redirect('shop:cart_detail')

def cart_remove(request, product_id):
    cart=request.session.get(settings.CART_SESSION_ID)
    if str(product_id) in cart:
        del cart[str(product_id)]
    request.session[settings.CART_SESSION_ID]=cart
    return redirect('shop:cart_detail')
def is_costumer(user):
    if user.is_authenticated and user.is_costumer:
        return True
    return False

@user_passes_test(is_costumer, login_url='/login/')
def order_create(request):
    cart = request.session.get(settings.CART_SESSION_ID)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.paid=True
            order.costumer=request.user.costumer
            order.save()

            for key,val in cart.items():
                product = Product.objects.get(id=int(key))
                OrderItem.objects.create(order=order,product=product,price=val['price'],quantity=val['quantity'])
            # Vider le panier
            del request.session[settings.CART_SESSION_ID]
            return render(request,'clients/payed.html', {'order': order})
    else:
        cart_total_price=0
        for key,val in cart.items():
            cart_total_price+= float(cart[key]['price']) * float(cart[key]['quantity'])
        form = OrderCreateForm()
        return render(request,'clients/processing_cmd.html',{'form': form,'cart_total_price':cart_total_price})


def order_history(request, user_id):
    orders = Order.objects.filter(costumer_id=user_id)

    return render(request, "clients/mescommandes.html", {'orders':orders})

backend/templates/clients/login.html
<!doctype html>
<html lang="en">
  <head>
    {% load crispy_forms_tags %} 
    {% load static %}
    <title>{% block title %} Login {% endblock  %}</title>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     {% block stylesheet %}
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	
	<link rel="stylesheet" href="{%static 'login/css/style.css' %}">
    {% endblock  %}
	</head>
	<body style="background-image: url(shop/images/hero-side-bg.png);">
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Connexion</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-6 col-lg-4">
					<div class="login-wrap p-0">
		      	<h3 class="mb-4 text-center">Have an account?</h3>
		      	<form action="{% url 'shop:login' %}" method="post" class="signin-form">
		      		<div class="form-group">
                        {{ form|crispy }}
                </div>
                {% csrf_token %}

	            <div class="form-group">
                    <input type="submit" value="Connexion" class="form-control btn btn-primary submit px-3">
	            </div>
	            <div class="form-group d-md-flex">
	            	<div class="w-50">
		            	<label class="checkbox-wrap checkbox-primary">Remember Me
									  <input type="checkbox" checked>
									  <span class="checkmark"></span>
									</label>
								</div>
	            </div>
	          </form>
	          <p class="w-100 text-center">&mdash; Vous n'avez pas de compte ? &mdash;</p>
	          <div class="social d-flex text-center">
                  <a href="{% url 'shop:register'%}" class="px-2 py-2 mr-md-1 rounded"><span ></span> S'inscrire</a>
                  <a href="{% url 'shop:shop'%}" class="px-2 py-2 mr-md-1 rounded"><span ></span> Retourner</a>
	          </div>
		      </div>
				</div>
			</div>
		</div>
	</section>
    {% block scripts %}

	<script src="{% static 'login/js/jquery.min.js' %}"></script>
  <script src="{% static 'login/js/popper.js' %}"></script>
  <script src="{% static 'login/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'login/js/main.js' %}"></script>
  {% endblock%}

	</body>
</html>

backend/templates/clients/mescommandes.html
{% extends 'clients/shop.html' %}
{% block title %} A6 Negoce {% endblock  %}
  {% block content %}
  
  <body class="sub_page">
    <div class="hero_area">
      <!-- header section strats -->
      <header class="header_section">
        <div class="container-fluid">
          <nav class="navbar navbar-expand-lg custom_nav-container">
            <a class="navbar-brand" href="{%url 'shop:shop'%}">
                
              {% load static %}
                          <img src="{% static 'shop/images/negoce.jpg' %}" alt="My image"/>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
  
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav  ">
                <li class="nav-item">
                  <a class="nav-link" href="{%url 'shop:shop'%}">Accueil </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{%url 'shop:productList'%}">Produits </a>
                </li>
                
                {% if request.user.is_authenticated and request.user.is_costumer%}
              <li class="nav-item active">
                <a class="nav-link" href=""> Mes commandes <span class="sr-only">(current)</span></a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="{%url 'shop:logout'%}">Logout</a>
              </li>
              {%endif%}
              <li class="nav-item">
                <a href="{%url 'shop:cart_detail'%}" class="nav-link" class="nav-link navbar-link-2 waves-effect">
                  
                  <i class="fas fa-shopping-cart"></i>
                  <span   class="badge badge-pill red">{{cart|length}}</span>
  
  
                </a>
                
              </li>
            </ul>
            
            <div class="user_option">
              
              <a href="">
                {% if request.user.is_authenticated and request.user.is_costumer%}
  
                Bienvenu {{request.user.first_name}}
                
                
                {%else%}
                  <span>
                    <a href="{%url 'shop:login'%}">Login </a>
                  </span>
                  {% endif %}
                </a>
               
                <form method="POST" action="{%url 'shop:rechercher'%}" class="form-inline my-2 my-lg-0 ml-0 ml-lg-4 mb-3 mb-lg-0">
                  {% csrf_token %}
                   <input class="form-control mr-sm-2" type="search" name ="cle" placeholder="Rechercher" aria-label="Rechercher">
                   
                   <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit"></button>
                 </form>
              </div>
            </div>
            <div>
              <div class="custom_menu-btn ">
                <button>
                  <span class=" s-1">
  
                  </span>
                  <span class="s-2">
  
                  </span>
                  <span class="s-3">
  
                  </span>
                </button>
              </div>
            </div>
  
          </nav>
        </div>
      </header>
      <!-- end header section -->
    </div>
  
<table class="table">
    <thead class="table-success">
      <tr>
       
        <th scope="col">Id</th>
        <th scope="col">Address</th>
        <th scope="col">Code postal</th>
        <th scope="col">City</th>
        <th scope="col">Created</th>
      </tr>
    </thead>
    <tbody>
        {%  for order in orders  %}
      <tr>
        <th scope="row"> {{ order.id }}</th>
        <td> {{ order.address }}</td>
        <td> {{ order.postal_code }}</td>
        <td>{{ order.city }}</td>
        <td> {{ order.created }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  
{% endblock %}

backend/templates/clients/product_list.html
{% extends 'clients/shop.html' %}
{% block title %} A6 Negoce  {% endblock  %}
  {% block content %}
  
<body class="sub_page">
  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container">
          <a class="navbar-brand" href="{%url 'shop:shop'%}">
              
            {% load static %}
                        <img src="{% static 'shop/images/negoce.jpg' %}" alt="My image"/>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  ">
              <li class="nav-item">
                <a class="nav-link" href="{%url 'shop:shop'%}">Accueil </a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{%url 'shop:productList'%}">Produits <span class="sr-only">(current)</span></a>
              </li>
              
              {% if request.user.is_authenticated and request.user.is_costumer%}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'shop:history' request.user.costumer.id %}"> Mes commandes </a>
            </li>
            
            <li class="nav-item">
              <a class="nav-link" href="{%url 'shop:logout'%}">Logout</a>
            </li>
            {%endif%}
            <li class="nav-item">
              <a href="{%url 'shop:cart_detail'%}" class="nav-link" class="nav-link navbar-link-2 waves-effect">
                
                <i class="fas fa-shopping-cart"></i>
                <span   class="badge badge-pill red">{{cart|length}}</span>


              </a>
              
            </li>
          </ul>
          
          <div class="user_option">
            
            <a href="">
              {% if request.user.is_authenticated and request.user.is_costumer%}

              Bienvenu {{request.user.first_name}}
              
              
              {%else%}
                <span>
                  <a href="{%url 'shop:login'%}">Login </a>
                </span>
                {% endif %}
              </a>
             
              <form method="POST" action="{%url 'shop:rechercher'%}" class="form-inline my-2 my-lg-0 ml-0 ml-lg-4 mb-3 mb-lg-0">
                {% csrf_token %}
                 <input class="form-control mr-sm-2" type="search" name ="cle" placeholder="Rechercher" aria-label="Rechercher">
                 
                 <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit"></button>
               </form>
            </div>
          </div>
          <div>
            <div class="custom_menu-btn ">
              <button>
                <span class=" s-1">

                </span>
                <span class="s-2">

                </span>
                <span class="s-3">

                </span>
              </button>
            </div>
          </div>

        </nav>
      </div>
    </header>
    <!-- end header section -->
  </div>



  <!-- brand section -->

  <section class="brand_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2>
          Nos produits
        </h2>
      </div>
      <div class="brand_container layout_padding2">
        {% for p in products %}
        <div class="box">
          <a href="">
            <div class="img-box">
              <img src="{{p.image.url}}" alt="">
            </div>
            <div class="detail-box">
              <h6 class="price">
                {{p.price}}DH
              </h6>
              <h6>
                {{p.name}}
              </h6>
            </div>
            
          </a>
          {% comment %} <form class="d-flex justify-content-left">
            <!-- Default input -->
            <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
            <button class="btn btn-primary btn-md my-0 p" type="submit">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </button>

          </form> {% endcomment %}
          
          <a href="{% url 'shop:cart_add' p.id %}" >
            <img src="https://img.icons8.com/ios-glyphs/30/000000/buy--v1.png"/>
          </a>
        </div>
        
        {% endfor %}

        
      </div>
      <a href="" class="brand-btn">
        See More
      </a>
    </div>
  </section>

  <!-- end brand section -->

{% endblock %}

backend/templates/clients/shopcart.html
<!doctype html>
                        <html>
                            <head>
                                <meta charset='utf-8'>
                                <meta name='viewport' content='width=device-width, initial-scale=1'>
                                {% load static %}
                                <title>{% block title %} Panier {% endblock  %}</title>
                                {% block stylesheet %}                                
                                <link href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' rel='stylesheet'>
                                <link href='https://use.fontawesome.com/releases/v5.7.2/css/all.css' rel='stylesheet'>
                                <link href='{% static "order.css" %}' rel='stylesheet'>
                                
                                {% endblock  %}
                                
                                
                                </head>
                                <body oncontextmenu='return false' class='snippet-body'>
                                <nav class="bg-white">
    <div class="d-flex align-items-center">
        <div class="logo"> <a href="{% url 'shop:shop' %}" class="text-uppercase">A6 negoce</a> </div>
        <div class="ml-auto"> <a href="#" class="text-uppercase">Checkout</a> </div>
    </div>
</nav>
<header>
    <div class="d-flex justify-content-center align-items-center pb-3">
        <div class="px-sm-5 px-2 active">PANIER  <span class="fas fa-check"></span></div>
        <div class="px-sm-5 px-2 ">CHECKOUT</div>
        <div class="px-sm-5 px-2">TERMINE</div>
    </div>
    <div class="progress">
        <div class="progress-bar-p bg-success" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
</header>
<div class="wrapper">
    <div class="h5 large">Votre panier</div>
    <div class="row">
        <div class="col-lg-6 col-md-8 col-sm-10 offset-lg-0 offset-md-2 offset-sm-1">
            <div class="mobile h5">Produits</div>
            <div id="details" class="bg-white rounded pb-5">
                <div id="cart" class="bg-white rounded">
                    {% for item in cart.values %}
                    {% with product=item.product %}
                    <div class="d-flex justify-content-between align-items-center">
                        
                        <div class="h6">Produit</div>
                        <div class="h6"> <a href="#">Supprimer</a> </div>
                    </div>
                    <div class="d-flex jusitfy-content-between align-items-center pt-3 pb-2 border-bottom">
                        <div class="item pr-2"> <img src="{% if product.image %}{{ product.image.url}} {% else %}{% static 'img/no_image.png' %}{% endif %}" alt="" width="80" height="80">
                            <div class="number">{{ item.quantity }}</div>
                        </div>
                        <div class="d-flex flex-column px-3"> <b class="h5">{{ product.name }}</b> <a href="#" class="h5 text-primary">{{ product.brand }}</a> </div>
                        
                    </div><div class="d-flex align-items-center">
                            <div class="display-5">Prix</div>
                            <div class="ml-auto font-weight-bold">{{ item.price }} DH</div>
                        </div>
                        <div class="d-flex align-items-center py-2">
                            <div class="display-5">Total</div>
                            <div class="ml-auto d-flex">
                                <div class="text-primary text-uppercase px-3">Mad</div>
                                <div class="font-weight-bold">{{ item.total_price }} DH</div>
                            </div>
                        </div>
                        
                        
                    
                         <form action="{% url 'shop:cart_update' product.id %}" method="post">
                        {% csrf_token %}
                        <input type="number" name="quantity" value="{{ item.quantity }}">
                       <div class="row pt-lg-3 pt-2 buttons mb-sm-0 mb-2"><input class="btn text-white ml-auto" type="submit" value="Modifer">
                    </form> 
                    <form action="{% url 'shop:cart_remove' product.id %}" method="post">
                        <input class="btn text-white ml-auto" type="submit" value="Supprimer">
                        {% csrf_token %}
                        </form></div>
               
                    {% endwith %}
                    {% endfor %}
                    
                   
                    
                </div>
            </div> <input type="checkbox" checked> <label>Shipping address is same as billing</label>
           
        </div>
        <div class="col-lg-6 col-md-8 col-sm-10 offset-lg-0 offset-md-2 offset-sm-1 pt-lg-0 pt-3">
            <div id="cart" class="bg-white rounded">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="h6">Cart Summary</div>
                    <div class="h6"> <a href="#">Edit</a> </div>
                </div>
                <div class="d-flex align-items-center">
                    <div class="display-5">Sous-total</div>
                    <div class="ml-auto font-weight-bold">{{cart_total_price}} DH</div>
                </div>
                <div class="d-flex align-items-center py-2 border-bottom">
                    <div class="display-5">Article</div>
                    <div class="ml-auto font-weight-bold">{{cart|length}}</div>
                </div>
                <div class="d-flex align-items-center py-2">
                    <div class="display-5">Total TTC</div>
                    <div class="ml-auto d-flex">
                    <div class="text-primary text-uppercase px-3">MAD</div>
                        <div class="font-weight-bold">{{cart_total_price}} DH</div>
                    </div>
                </div>
            </div>
            
            <div class="row pt-lg-3 pt-2 buttons mb-sm-0 mb-2">
                <div class="col-md-6">
                    <a href="{%url 'shop:productList'%}" class="btn text-uppercase">POURSUIVRE VOS ACHATS</a>
                </div>
                <div class="col-md-6 pt-md-0 pt-3">
                    <a href="{% url 'shop:order_create' %}" class="btn text-white ml-auto"> <span class="fas fa-lock"></span> Finaliser votre commande </a>
                </div>
            </div>
            <div class="text-muted pt-3" id="mobile"> <span class="fas fa-lock"></span> Your information is save </div>
        </div>
    </div>
    <div class="text-muted"> <span class="fas fa-lock"></span> Your information is save </div>
</div>
                                 {% block javascript %}
                                <script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
                                <script type='text/javascript' src='https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js'></script>
                                <script type='text/javascript'></script>
                                {% endblock %}



                                </body>
                            </html>






















    